name: Cucumber (Behave) Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Run Behave with a virtual display so non-headless Chrome works in CI
      - name: Run Behave (Cucumber)
        run: |
          xvfb-run -a behave -f progress

      # Save screenshots/logs on failure (if you add them later)
      - name: Upload test artifacts (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: behave-artifacts
          path: |
            ./screenshots/**
            ./logs/**
          if-no-files-found: ignore
